### ISSUE TITLE
X = -1, Y = 1 is front left

### ISSUE THREAD

**Issue by mzed** [immersive-audio-live/ADM-OSC#18]
I don't know we've made it explicit that Cartesian coordinates are
```
(-1, 1) --------- (1, 1)
    |                |
    |                |
    |                |
    |                |
(-1, -1) ---------(1, -1)
```

**Comment by lzwicker** [comment]
Agreed, should be noted somewhere and if someone uses different orientation the sender needs to normalize it accordingly to the ADM-OSC spec.

**Comment by lzwicker** [comment]
Agreed, should be noted somewhere and if someone uses different orientation the sender needs to normalize it accordingly to the ADM-OSC spec.

**Comment by davemar-bbc** [comment]
And positive azimuth angles are to the left. So a front-left speaker is +30degs.

**Comment by mzed** [comment]
Maybe we should add a page to the site with those graphics?  I think this issue can be closed.
