### ISSUE TITLE
Recommendations for frame rate

### ISSUE THREAD

**Issue by mzed** [immersive-audio-live/ADM-OSC#30]
20 fps?  10 - 30 fps?

**Comment by madees** [comment]
Having some recommendations like:
- feature to set/limit transmitter rate
- feature to get the maximum receiving rate of renderer
- default/typical rate examples (s-ADM frame rate ? 20-50 ms)
- recommend strategies to manage rate (too high : avoid flooding by decimating, 
Too low: interpolate...)

**Comment by mzed** [comment]
The Dolby Atmos ADM profile says:

> The sampling period should be less than 20 milliseconds. Sampling is optional if the metadata state
> remains unchanged.

20 ms seems like a decent recommendation. 

It's tempting to add some support for interpolation to ADM-OSC, but the Dolby profile does not support setting the interpolation value. The interpolate over 250 samples at 48k, or 500 samples at 96k.

**Comment by mzed** [comment]
The 1.0 spec recommends 20ms.
