### ISSUE TITLE
Mute ADM object

### ISSUE THREAD

**Issue by lzwicker** [immersive-audio-live/ADM-OSC#31]
We started to use ADM-OSC with tracking systems to start with a clean and easy foundation for both sides.
One addition being handy would be muting and object, e.g.

`/adm/obj/(k)/mute bool`
payload being 0/1 **or** false/true

I would love to settle on false/true, but experienced that there are quite a lot of systems out there having trouble to handle boolean false/true.

Example: `/adm/obj/1/mute 1`

**Comment by madees** [comment]
sounds great, should be included in 1.0

**Comment by JGaudin** [comment]
I agree, and easy to support in a 1.0 version.
I also would like to emphasize that most consumer programming tools (touchOSC, MAX, Lemur, Pure Data) dont use booleans, so I still believe an integer argument is a must, but we could have both arguments (but that feels redundant)

**Comment by mzed** [comment]
I can't think of any reason not to include this message.

An integer makes sense to me because:
- ADM itself uses 0/1 rather than false/true
- We're not using bools in the current 0.4 spec

"1" would mean that the object is muted.

**Comment by mzed** [comment]
This has been announced in the 1.0 spec, so this issue can be closed.
