### ISSUE TITLE
Language standard?

### ISSUE THREAD

**Issue by mzed** [immersive-audio-live/ADM-OSC#8]
Version 0.5 proposes some language messages. We should pick a standard for those. ISO 639-1?

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by firthm01** [comment]
We should keep parameters compliant with BS.2076 to avoid confusion and conflict if ADM-OSC becomes a standard. For language attributes, it states; 

> The language code is given as a 2- or 3-character code as specified by ISO 639-1 or ISO 639-2. Both ISO 639-2/B and ISO 639-2/T may be used.
